### ISSUE TITLE
License

### ISSUE THREAD

**Issue by grst** [maluramichael/py-sma-modbus#2]
Hi @maluramichael, 

thanks for putting this repo together! Under which license do you provide the code? Could you consider adding a license file to the repo? 

I would like to adapt this code for a private project (and potentially make it public on GitHub again) -- technically I'm not allowed to do that without an open source license. 

Thanks, 
Gregor

**Comment by maluramichael** [comment]
Hey Gregor. Sure. Ill add the MIT license. Go for it :)
